PROC: Created for Mysql with PhpMyDmin
Proc Name: FIND_WEATHER_BY_ZIP_CODE_AND_WEATHER_DATE
DROP PROCEDURE `FIND_WEATHER_BY_ZIP_CODE_AND_WEATHER_DATE`;
CREATE DEFINER=`root`@`localhost` PROCEDURE `FIND_WEATHER_BY_ZIP_CODE_AND_WEATHER_DATE`(IN `DATE_IN` DATE, IN `ZIP_CODE` VARCHAR(10)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER SELECT W.* FROM WEATHER W
INNER JOIN ZIP_CODE Z
ON Z.ZIP_CODE = W.ZIP_CODE
WHERE W.DATE=DATE_IN AND W.ZIP_CODE=ZIP_CODE


proc name: FIND_ALL_ZIP_CODES_WITH_WEATHER
DROP PROCEDURE `FIND_ALL_ZIP_CODES_WITH_WEATHER`;
CREATE DEFINER=`root`@`localhost` PROCEDURE `FIND_ALL_ZIP_CODES_WITH_WEATHER`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER SELECT Z.ZIP_CODE,Z.zip_location,
W.min_temperature,W.max_temperature,W.date
FROM ZIP_CODE Z
LEFT JOIN WEATHER W
ON Z.zip_code=W.zip_code